group_meeting/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'meeting.views.index'),
    url(r'^register/$', 'meeting.views.register', name='register'),
    url(r'^login/$', 'meeting.views.user_login', name='login'),
    url(r'^logout/$', 'meeting.views.user_logout', name='logout'),
    url(r'^about/$', 'meeting.views.about', name='about'),
    url(r'^create-project/$', 'meeting.views.create_project', name='create-project'),
    url(r'^add-meeting/$', 'meeting.views.add_meeting', name='add-meeting'),
    url(r'^add-file/$', 'meeting.views.add_file', name='add-file'),
    url(r'^add-note/$', 'meeting.views.add_note', name='add-note'),
    url(r'^add-user/$', 'meeting.views.add_user', name='add-user'),
    url(r'^calendar/$', 'meeting.views.calendar', name='calendar'),
    url(r'^notes/$', 'meeting.views.notes', name='notes'),
    url(r'^files/$', 'meeting.views.files', name='files'),
    url(r'^project-home/$', 'meeting.views.home', name='home'),
    url(r'^delete-note/$', 'meeting.views.delete_note', name='delete-note'),
    url(r'^delete-file/$', 'meeting.views.delete_file', name='delete-file'),
    url(r'^delete-meeting/$', 'meeting.views.delete_meeting', name='delete-meeting'),
    url(r'^delete-project/$', 'meeting.views.delete_project', name='delete-project'),
    url(r'^edit-note/(?P<id>\d+)/$', 'meeting.views.edit_note', name='edit-note'),
    url(r'^edit-file/(?P<id>\d+)/$', 'meeting.views.edit_file', name='edit-file'),
    url(r'^edit-meeting/(?P<id>\d+)/$', 'meeting.views.edit_meeting', name='edit-meeting'),
    url(r'^edit-project/(?P<id>\d+)/$', 'meeting.views.edit_project', name='edit-project'),
    url(r'^finish-project/$', 'meeting.views.finish_project', name='finish-project'),
    url(r'^open-project/$', 'meeting.views.open_project', name='open-project')
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT}),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
    )

meeting/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, date
from django.utils import timezone


DEFAULT_USER_ID = 1
DEFAULT_PROJECT_ID = 1


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __unicode__(self):
        return self.user.username


class Project(models.Model):
    name = models.CharField(max_length=128)
    owner = models.ForeignKey(UserProfile, related_name="proj_owner")
    users = models.ManyToManyField(UserProfile)
    due_date = models.DateTimeField(blank=True, null=False)
    completed = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name


class Note(models.Model):
    project = models.ForeignKey('Project', default=DEFAULT_PROJECT_ID)
    date_added = models.DateTimeField(default=datetime.now())
    added_by = models.ForeignKey('UserProfile', default=DEFAULT_USER_ID)
    title = models.CharField(max_length=128)
    content = models.TextField()

    def __unicode__(self):
        return self.title


def file_path(instance, filename):
    return '/'.join(['files', str(instance.project.name.replace(" ", "_")), filename])


class File(models.Model):
    project = models.ForeignKey('Project', default=DEFAULT_PROJECT_ID)
    date_added = models.DateTimeField(default=datetime.now())
    added_by = models.ForeignKey('UserProfile', default=DEFAULT_USER_ID)
    title = models.CharField(max_length=128)
    file = models.FileField(upload_to=file_path)

    def __unicode__(self):
        return self.title


class Meeting(models.Model):
    project = models.ForeignKey('Project', default=DEFAULT_PROJECT_ID)
    date_added = models.DateTimeField(default=datetime.now())
    added_by = models.ForeignKey('UserProfile', default=DEFAULT_USER_ID)
    date_begin = models.DateTimeField()
    date_end = models.DateTimeField()
    title = models.CharField(max_length=128)
    place = models.CharField(max_length=128)
    description = models.TextField()

    def __unicode__(self):
        return self.title

    def begin_format(self):
        date_begin = timezone.localtime(self.date_begin)
        return '%s' % date_begin.strftime('%Y-%m-%dT%H:%M:%S')

    def end_format(self):
        date_emd = timezone.localtime(self.date_end)
        return '%s' % date_end.strftime('%Y-%m-%dT%H:%M:%S')


class Action(models.Model):
    project = models.ForeignKey('Project', default=DEFAULT_PROJECT_ID)
    date_occurred = models.DateTimeField(default=datetime.now())
    by_who = models.ForeignKey('UserProfile', default=DEFAULT_USER_ID)
    action_performed = models.CharField(max_length=128)
    category = models.CharField(max_length=128)
    title = models.CharField(max_length=128)

meeting/forms.py
from meeting.models import UserProfile, Project, Note, File, Meeting, Action
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    username = forms.CharField(help_text="Please enter a username.")
    email = forms.EmailField(help_text="Please enter your email.")
    password = forms.CharField(widget=forms.PasswordInput(), help_text="Please enter a password.")

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class UserProfileForm(forms.ModelForm):
    picture = forms.ImageField(help_text="Select a profile image to upload.", required=False)

    class Meta:
        model = UserProfile
        fields = ['picture']


class ProjectForm(forms.ModelForm):
    name = forms.CharField(help_text="Please enter a project name.")
    due_date = forms.DateTimeField(widget=forms.DateTimeInput(format='%m/%d/%Y %H:%M %p'), input_formats=['%m/%d/%Y %H:%M %p'], localize=True)

    class Meta:
        model = Project
        fields = ['name', 'due_date']


class NotesForm(forms.ModelForm):
    title = forms.CharField(help_text="Please enter the title of your note.")
    content = forms.Textarea()

    class Meta:
        model = Note
        fields = ['title', 'content']


class FilesForm(forms.ModelForm):
    title = forms.CharField(help_text="Please enter a title for your file.")
    file = forms.FileField(help_text="Upload your file.")

    class Meta:
        model = File
        fields = ['title', 'file']


class MeetingForm(forms.ModelForm):
    title = forms.CharField(help_text="Please enter a title for your meeting.")
    date_begin = forms.DateTimeField(widget=forms.DateTimeInput(format='%m/%d/%Y %H:%M %p'), input_formats=['%m/%d/%Y %H:%M %p'], localize=True)
    date_end = forms.DateTimeField(widget=forms.DateTimeInput(format='%m/%d/%Y %H:%M %p'), input_formats=['%m/%d/%Y %H:%M %p'], localize=True)
    place = forms.CharField(help_text="Enter the location.")
    description = forms.Textarea()

    class Meta:
        model = Meeting
        fields = ['title', 'date_begin', 'date_end', 'place', 'description']


class AddUserForm(forms.ModelForm):
    user = forms.CharField()

    class Meta:
        model = Project
        fields = ['user']


class ActionForm(forms.ModelForm):
    class Meta:
        model = Action
        fields = []


class DeleteNoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = []


class DeleteFileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = []


class DeleteMeetingForm(forms.ModelForm):
    class Meta:
        model = Meeting
        fields = []


class FinishProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = []


class DeleteProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = []

meeting/views.py
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from meeting.forms import UserForm, UserProfileForm, ProjectForm, NotesForm, FilesForm, MeetingForm, AddUserForm, \
    ActionForm, DeleteNoteForm, FinishProjectForm, DeleteProjectForm
from meeting.models import UserProfile, Project, Note, Meeting, File, Action
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages


# Create your views here.
@login_required(login_url='/login/')
def index(request):
    user = UserProfile.objects.get(user=request.user)
    projects = user.project_set.all()
    active_projects = projects.filter(completed=False)
    completed_projects = projects.filter(completed=True)
    pid = request.GET.get('pid')
    request.session['pid'] = pid
    if pid:
        display_project = projects.filter(id=pid)
        actions = Action.objects.filter(project=pid).order_by('-date_occurred')[:15]
    else:
        display_project = None
        actions = None

    print pid
    return render(request, 'meeting/index.html', {
        'projects': projects,
        'active_projects': active_projects,
        'completed_projects': completed_projects,
        'display_project': display_project,
        'actions': actions
    })


def about(request):
    return render(request, 'meeting/about.html')


def register(request):
    context = RequestContext(request)
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print user_form.errors, profile_form.errors
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render_to_response('meeting/register.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered
    }, context)


def user_login(request):
    context = RequestContext(request)
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                return HttpResponse("Your account is disabled.")
        else:
            print "Invalid login details: {0}, {1}".format(username, password)
            return HttpResponse("Invalid login details supplied.")
    else:
        return render_to_response('meeting/login.html', {}, context)


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')


@login_required(login_url='/login/')
def create_project(request):
    context = RequestContext(request)
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.owner = UserProfile.objects.get(user=request.user)
            project.save()
            project.users.add(UserProfile.objects.get(user=request.user))
            project.save()
            return HttpResponseRedirect('/')
        else:
            print form.errors
    else:
        form = ProjectForm()
    return render_to_response('meeting/create-project.html', {'form': form}, context)


@login_required(login_url='/login/')
def add_user(request):
    context = RequestContext(request)
    if request.method == 'POST':
        form = AddUserForm(request.POST)
        if form.is_valid():
            pid = request.session.get('pid')
            if not pid:
                messages.add_message(request, messages.WARNING, 'You need to select a project before you can add a user.')
                return HttpResponseRedirect('/')
            else:
                project = Project.objects.get(id=pid)
                this = form.cleaned_data['user']
                if User.objects.filter(username=this):
                    user = User.objects.filter(username=this)
                else:
                    print "invalid username"
                project.users.add(UserProfile.objects.get(user=user))
                project.save()
                return HttpResponseRedirect('/?pid=' + str(project.id))

        else:
            print form.errors
    else:
        form = AddUserForm()
    return render_to_response('meeting/add-user.html', {'form': form}, context)


@login_required(login_url='/login/')
def add_meeting(request):
    context = RequestContext(request)
    if request.method == 'POST':
        form = MeetingForm(request.POST)
        action = ActionForm(request.POST)
        if form.is_valid():
            pid = request.session.get('pid')
            if not pid:
                messages.add_message(request, messages.WARNING, 'You need to select a project before you can add a meeting.')
                return HttpResponseRedirect('/')
            else:
                meeting = form.save(commit=False)
                meeting.project = Project.objects.get(id=pid)
                meeting.added_by = UserProfile.objects.get(user=request.user)
                meeting.save()
                action = action.save(commit=False)
                action.project = Project.objects.get(id=pid)
                action.by_who = UserProfile.objects.get(user=request.user)
                action.category = "Calendar"
                action.action_performed = "Added"
                action.title = meeting.title
                action.save()
                return HttpResponseRedirect('/?pid=' + pid)
        else:
            print form.errors
    else:
        form = MeetingForm()
    return render_to_response('meeting/add-meeting.html', {'form': form}, context)


def edit_meeting(request, id=None):
    meeting = Meeting.objects.get(pk=id)
    context = RequestContext(request)
    if request.method == 'POST':
        form = MeetingForm(request.POST, instance=meeting)
        action = ActionForm(request.POST)
        if form.is_valid():
            form.save()
            action = action.save(commit=False)
            action.project = Project.objects.get(id=meeting.project.id)
            action.by_who = UserProfile.objects.get(user=request.user)
            action.category = "Calendar"
            action.action_performed = "Edited"
            action.title = meeting.title
            action.save()
            return HttpResponseRedirect('/?pid=' + str(meeting.project.id))
        else:
            print form.errors
    else:
        form = MeetingForm(instance=meeting)
    return render_to_response('meeting/edit-meeting.html', {'form': form}, context)


@login_required(login_url='/login/')
def add_file(request):
    context = RequestContext(request)
    if request.method == 'POST':
        form = FilesForm(request.POST, request.FILES)
        action = ActionForm(request.POST)
        if form.is_valid():
            pid = request.session.get('pid')
            if not pid:
                messages.add_message(request, messages.WARNING, 'You need to select a project before you can add a file.')
                return HttpResponseRedirect('/')
            else:
                fileform = form.save(commit=False)
                fileform.project = Project.objects.get(id=pid)
                fileform.added_by = UserProfile.objects.get(user=request.user)
                if 'file' in request.FILES:
                    fileform.file = request.FILES['file']
                else:
                    print "no"
                fileform.save()
                action = action.save(commit=False)
                action.project = Project.objects.get(id=pid)
                action.by_who = UserProfile.objects.get(user=request.user)
                action.category = "File"
                action.action_performed = "Added"
                action.title = fileform.title
                action.save()
                return HttpResponseRedirect('/?pid=' + pid)
        else:
            print form.errors
    else:
        form = FilesForm()
    return render_to_response('meeting/add-file.html', {'form': form}, context)


def edit_file(request, id=None):
    file = File.objects.get(pk=id)
    context = RequestContext(request)
    if request.method == 'POST':
        form = FilesForm(request.POST, instance=file)
        action = ActionForm(request.POST)
        if form.is_valid():
            form.save()
            action = action.save(commit=False)
            action.project = Project.objects.get(id=file.project.id)
            action.by_who = UserProfile.objects.get(user=request.user)
            action.category = "Notes"
            action.action_performed = "Edited"
            action.title = file.title
            action.save()
            return HttpResponseRedirect('/?pid=' + str(file.project.id))
        else:
            print form.errors
    else:
        form = FilesForm(instance=file)
    return render_to_response('meeting/edit-file.html', {'form': form}, context)


@login_required(login_url='/login/')
def add_note(request):
    context = RequestContext(request)
    if request.method == 'POST':
        form = NotesForm(request.POST)
        action = ActionForm(request.POST)
        if form.is_valid():
            pid = request.session.get('pid')
            if not pid:

templates/meeting/about.html
{% extends 'base.html' %}

{% block title %} | About{% endblock %}

{% block content %}
    <div class="col-lg-12">
        <div class="well" style="text-align: center;">
            <h1>What is Project Central?</h1>
            <p>Nulla turpis, bibendum mi posuere, ultrices primis turpis aptent ridiculus.</p>

            <p>Etiam interdum rhoncus. Proin mollis montes id lorem rutrum.</p>

            <p>Quam pulvinar lacinia ante pretium facilisi mus placerat senectus ipsum commodo.</p>
        </div>
    </div>
{% endblock %}

templates/meeting/add-meeting.html
{% extends 'base.html' %}
{% load addcss %}
{% load static %}

{% block styles %}
{% endblock %}

{% block content %}
    <div class="container login well">
        <h1>Add a Meeting</h1>

        <form id="meeting_form" method="post" action="/add-meeting/">

            {% csrf_token %}

            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.label_tag }}
                {{ field | addcss:"form-control" }}
                <br/>
            {% endfor %}

            <br />

            <input class="btn btn-primary" type="submit" name="submit" value="Create Meeting" />
        </form>
    <script type="text/javascript">
        $(function () {
            $('#id_date_begin').datetimepicker();
            $('#id_date_end').datetimepicker();
            $("#id_date_begin").on("dp.change",function (e) {
               $('#id_date_end').data("DateTimePicker").setMinDate(e.date);
            });
            $("#id_date_end").on("dp.change",function (e) {
               $('#id_date_begin').data("DateTimePicker").setMaxDate(e.date);
            });
        });
    </script>
    </div><!-- /container -->
{% endblock %}

templates/meeting/add-note.html
{% extends 'base.html' %}
{% load addcss %}
{% load static %}

{% block styles %}
{% endblock %}

{% block content %}
    <div class="container login well">
        <h1>Add a Note</h1>

        <form id="note_form" method="post" action="/add-note/">

            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field | addcss:"form-control"}}
                <br/>
            {% endfor %}

            <br />

            <input class="btn btn-primary" type="submit" name="submit" value="Create Note" />
        </form>
    </div><!-- /container -->
{% endblock %}

templates/meeting/calendar.html
<div id="display">
    <div id="meetingModal"></div>
    <script>
        $(document).ready(function() {
            $('#calendar').fullCalendar({
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay'
                },
                eventClick: function(event, jsEvent, view) {
                    if (event.shown == false) {
                        var display = "Where: " + event.place + "<br/>" +
                                "From: " + event.start_date + "<br/>" +
                                "To: " + event.end_date + "<br/>" +
                                "Description: " + event.description + "<br/>" +
                                "<hr/>" +
                                "<a href='/edit-meeting/" + event.id + "' type='submit' class='btn btn-info'><i class='glyphicon glyphicon-pencil'></i> Edit</a>" +
                                "<button type='submit' class='btn btn-danger' style='float: right;' onclick='deleteMeeting(" + event.id + ");'>Delete <i class='glyphicon glyphicon-trash'></i></button>"
                        $(this).popover({html: true, title: event.title, placement: 'top', container: 'body', content: display}).popover('show');
                        event.shown = true;
                        $('#calendar').fullCalendar('updateEvent', event);
                    }
                    else {
                        $('.popover').popover('destroy');
                        event.shown = false;
                        $('#calendar').fullCalendar('updateEvent', event);
                    }
                },
                defaultDate: Date(),
                editable: false,
                eventLimit: true,
                timezone: 'America/Chicago',
                ignoreTimezone: false,
                events: [
                    {% for meeting in meetings %}
                        {
                            title: '{{ meeting.title }}',
                            start: '{{ meeting.begin_format }}',
                            end: '{{ meeting.end_format }}',
                            id: '{{ meeting.id }}',
                            description: '{{ meeting.description }}',
                            place: '{{ meeting.place }}',
                            start_date: '{{ meeting.begin_format }}',
                            end_date: '{{ meeting.date_end }}',
                            shown: false
                        }{% if not forloop.last %},{% endif %}
                    {% endfor %}
                ]
            });

        });
    </script>

    <div id='calendar' style="max-width: 700px; margin: 0 auto;"></div>
    <br/><br/>
    <a href="/add-meeting/" class="btn btn-primary">Add a Meeting</a>

</div>

templates/meeting/create-project.html
{% extends 'base.html' %}
{% load addcss %}
{% load static %}

{% block styles %}
{% endblock %}

{% block content %}
    <div class="container login well">
        <h1>Create a Project</h1>

        <form id="project_form" method="post" action="/create-project/">

            {% csrf_token %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.label_tag }}
                {{ field | addcss:"form-control"}}
                <br/>
            {% endfor %}

            <br />

            <input class="btn btn-primary" type="submit" name="submit" value="Create Project" />
        </form>

    <script type="text/javascript">
        $(function () {
            $('#id_due_date').datetimepicker();
        });
    </script>

    </div><!-- /container -->
{% endblock %}

templates/meeting/delete-note.html
<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Delete Note</h4>
            </div>
            <div class="modal-body">
                <p>You sure that you want to delete this note? You will not be able to undo this...</p>
            </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">No, cancel</button>
            <form id="delete_note_form" method="post" action="/delete-note/" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="note-id" value="{{ nid }}">
                <input class="btn btn-danger" type="submit" name="submit" value="Yes, delete" />
            </form>
        </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

templates/meeting/edit-meeting.html
{% extends 'base.html' %}
{% load addcss %}
{% load static %}

{% block styles %}
{% endblock %}

{% block content %}
    <div class="container login well">
        <h1>Edit Meeting</h1>

        <form id="meeting_form" method="post" action=".">

            {% csrf_token %}

            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.label_tag }}
                {{ field | addcss:"form-control" }}
                <br/>
            {% endfor %}

            <br />

            <input class="btn btn-primary" type="submit" name="submit" value="Edit Meeting" />
        </form>
    <script type="text/javascript">
        $(function () {
            $('#id_date_begin').datetimepicker();
            $('#id_date_end').datetimepicker();
            $("#id_date_begin").on("dp.change",function (e) {
               $('#id_date_end').data("DateTimePicker").setMinDate(e.date);
            });
            $("#id_date_end").on("dp.change",function (e) {
               $('#id_date_begin').data("DateTimePicker").setMaxDate(e.date);
            });
        });
    </script>
    </div><!-- /container -->
{% endblock %}

templates/meeting/edit-project.html
{% extends 'base.html' %}
{% load addcss %}
{% load static %}

{% block styles %}
{% endblock %}

{% block content %}
    <div class="container login well">
        <h1>Edit Project</h1>

        <form id="project_form" method="post" action=".">

            {% csrf_token %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.label_tag }}
                {{ field | addcss:"form-control"}}
                <br/>
            {% endfor %}

            <br />

            <input class="btn btn-primary" type="submit" name="submit" value="Edit Project" />
        </form>

    <script type="text/javascript">
        $(function () {
            $('#id_due_date').datetimepicker();
        });
    </script>

    </div><!-- /container -->
{% endblock %}

templates/meeting/files.html
<h3>Files</h3>
<div>
    <div id="fileModal"></div>
    {% if not files %}
        <p>No files for this project...</p>
    {% else %}
        {% for file in files %}
            <h4>{{ file.title }}</h4>
            <a href="{{ file.file.url }}" class="btn btn-primary" target="_blank">
                Download <i class="glyphicon glyphicon-download"></i>
            </a>
            <a href="/edit-file/{{ file.id }}" class="btn btn-info">
                <i class="glyphicon glyphicon-pencil"></i> Edit
            </a>
            <button type="submit" class="btn btn-danger" onclick="deleteFile({{ file.id }});">
                Delete <i class="glyphicon glyphicon-trash"></i>
            </button>
            <hr/>
        {% endfor %}
    {% endif %}
    <br/><br/>
    <a href="/add-file/" class="btn btn-primary">Add a File</a>
</div>

templates/meeting/finish-project.html
<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span></button>
                <h4 class="modal-title">Finish Project</h4>
            </div>
            <div class="modal-body">
                <p>Click "Finish" to mark the project as finished.</p>
            </div>
            <div class="modal-footer">
                <form id="finish_project_form" method="post" action="/finish-project/">
                    {% csrf_token %}
                    <input type="hidden" name="project-id" value="{{ pid }}">
                </form>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button class="btn btn-success" type="submit" name="submit" form="finish_project_form">Finish</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

templates/meeting/notes.html
<h3>Notes</h3>

<div class="panel-group" id="accordion">
    <div id="noteModal"></div>
    {% if not notes %}
        <p>No notes for this project...</p>
    {% else %}
        {% for note in notes %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapse-{{ note.id }}">
                            {{ note.title }}
                        </a>
                    </h4>
                </div>
                <div id="collapse-{{ note.id }}" class="panel-collapse collapse">
                    <div class="panel-body">
                        {{ note.content }}
                        <br/><br/>
                        <a href="/edit-note/{{ note.id }}" class="btn btn-info">
                          <i class="glyphicon glyphicon-pencil"></i> Edit
                        </a>
                        <button type="submit" class="btn btn-danger" style="float: right;" onclick="deleteNote( {{ note.id }});">
                          Delete <i class="glyphicon glyphicon-trash"></i>
                        </button>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    <br/><br/>
    <a href="/add-note/" class="btn btn-primary">Add a Note</a>
</div>